package com.celements.javascript;

import static com.google.common.base.Predicates.*;
import static java.util.Objects.*;

import java.io.IOException;
import java.io.InputStream;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.function.Supplier;
import java.util.stream.Stream;

import javax.annotation.PostConstruct;
import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.ResourcePatternResolver;
import org.springframework.stereotype.Service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.common.base.Suppliers;

import one.util.streamex.EntryStream;
import one.util.streamex.StreamEx;

/**
 * Resolves frontend JavaScript & CSS resources based on the vite manifest file.
 *
 * The manifest file is generated by vite during the build process and contains mappings from source
 * files to their corresponding production files with hashed names.
 *
 * @see https://vite.dev/guide/backend-integration.html#:~:text=example%20manifest
 */
@Service
public class FrontendResourceResolver {

  private static final Logger LOGGER = LoggerFactory.getLogger(FrontendResourceResolver.class);

  private static final String MANIFEST_PATH = "/resources/dist/.vite/manifest*.json";
  private static final String MANIFEST_KEY_PREFIX = "src/main/frontend/";
  private static final String SOURCE_PREFIX = ":frontend/";
  private static final String TARGET_DIR = "dist/";

  private final ResourcePatternResolver resourceLoader;
  private final ObjectMapper objectMapper;

  // ":frontend/file.ts" -> ("dist/file.a8b3.mjs", ["dist/assets/file.a8b3.css"])
  private final Supplier<Map<String, FrontendResource>> manifest = Suppliers.memoize(
      this::readManifestFiles);

  @Inject
  public FrontendResourceResolver(ResourcePatternResolver resourceLoader) {
    this.resourceLoader = resourceLoader;
    this.objectMapper = new ObjectMapper();
  }

  @PostConstruct
  public void init() {
    getManifest();
  }

  public Map<String, FrontendResource> getManifest() {
    return manifest.get();
  }

  /**
   * Resolves a frontend source path to its emitted dist files.
   *
   * @param sourcePath
   *          e.g. ":frontend/file.ts"
   *
   * @return The resolved frontend resource with JS and CSS dist paths, e.g.
   *         "dist/file.a8b3.mjs" and ["dist/assets/file.a8b3.css"]
   */
  public Optional<FrontendResource> get(String sourcePath) {
    return Optional.ofNullable(getManifest().get(sourcePath));
  }

  public boolean isFrontendSource(String path) {
    return requireNonNullElse(path, "").trim().startsWith(SOURCE_PREFIX);
  }

  private Map<String, FrontendResource> readManifestFiles() {
    Resource[] resources;
    try {
      resources = resourceLoader.getResources(MANIFEST_PATH);
    } catch (IOException e) {
      throw new IllegalStateException("Failed loading frontend manifest files", e);
    }
    var map = StreamEx.of(resources)
        .filter(Resource::exists)
        .flatMap(this::readJson)
        .flatMapToEntry(json -> new ViteManifest(json).frontendResources())
        .toImmutableMap(); // ISE on duplicate keys, we expect unique source files
    LOGGER.info("readManifest - {}", map);
    return map;
  }

  private Stream<JsonNode> readJson(Resource resource) {
    try (InputStream is = resource.getInputStream()) {
      return Stream.ofNullable(objectMapper.readTree(is));
    } catch (IOException e) {
      LOGGER.error("Failed reading JSON from resource [{}]", resource.getFilename(), e);
      return Stream.empty();
    }
  }

  public record FrontendResource(String jsPath, List<String> cssPaths) {}

  static final class ViteManifest {

    private final JsonNode manifest;

    ViteManifest(JsonNode manifest) {
      this.manifest = manifest;
    }

    Map<String, FrontendResource> frontendResources() {
      return EntryStream.of(manifest.fields())
          .mapToValue(ViteManifestEntry::new)
          .mapToKeyPartial((key, entry) -> entry.sourcePath())
          .mapToValuePartial((sourcePath, entry) -> entry.jsPath()
              .map(jsPath -> toFrontendResource(jsPath, entry)))
          .toImmutableMap();
    }

    private FrontendResource toFrontendResource(String jsPath, ViteManifestEntry entry) {
      var cssPaths = collectCssPaths(entry).distinct().toList();
      return new FrontendResource(jsPath, cssPaths);
    }

    private Stream<String> collectCssPaths(ViteManifestEntry entry) {
      return collectCssPaths(entry, new HashSet<>());
    }

    private Stream<String> collectCssPaths(ViteManifestEntry entry, Set<String> visited) {
      if (!visited.add(entry.key())) {
        return Stream.empty();
      }
      return StreamEx.of(entry.imports()
          .flatMap(k -> entry(k).stream())
          .flatMap(e -> collectCssPaths(e, visited)))
          .append(entry.cssPaths());
    }

    private Optional<ViteManifestEntry> entry(String key) {
      return Optional.ofNullable(manifest.get(key))
          .map(json -> new ViteManifestEntry(key, json));
    }
  }

  record ViteManifestEntry(String key, JsonNode json) {

    private static final String FIELD_FILE = "file";
    private static final String FIELD_CSS = "css";
    private static final String FIELD_IMPORTS = "imports";

    Optional<String> sourcePath() {
      return Optional.ofNullable(key)
          .filter(k -> k.startsWith(MANIFEST_KEY_PREFIX))
          .map(k -> k.replaceFirst(MANIFEST_KEY_PREFIX, SOURCE_PREFIX));
    }

    Optional<String> jsPath() {
      return getNode(FIELD_FILE).map(this::toTargetPath);
    }

    Stream<String> cssPaths() {
      return getArray(FIELD_CSS).map(this::toTargetPath).filter(Objects::nonNull);
    }

    public Stream<String> imports() {
      return getArray(FIELD_IMPORTS).map(JsonNode::asText).filter(not(String::isEmpty));
    }

    private Optional<JsonNode> getNode(String name) {
      return Optional.ofNullable(json.get(name));
    }

    private Stream<JsonNode> getArray(String fieldName) {
      return getNode(fieldName)
          .filter(JsonNode::isArray)
          .stream()
          .map(JsonNode::elements)
          .flatMap(StreamEx::of);
    }

    private String toTargetPath(JsonNode node) {
      return Optional.ofNullable(node)
          .map(JsonNode::asText)
          .filter(not(String::isEmpty))
          .map(file -> TARGET_DIR + file)
          .orElse(null);
    }
  }
}
