package com.celements.javascript;

import static java.util.Objects.*;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Optional;
import java.util.function.Supplier;
import java.util.stream.Stream;

import javax.annotation.PostConstruct;
import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.ResourcePatternResolver;
import org.springframework.stereotype.Service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.common.base.Suppliers;

import one.util.streamex.StreamEx;

/**
 * Resolves frontend JavaScript & CSS resources based on the vite manifest file.
 *
 * The manifest file is generated by vite during the build process and contains mappings from source
 * files to their corresponding production files with hashed names.
 *
 * @see https://vite.dev/guide/backend-integration.html#:~:text=example%20manifest
 */
@Service
public class FrontendResourceResolver {

  private static final Logger LOGGER = LoggerFactory.getLogger(FrontendResourceResolver.class);

  private static final String MANIFEST_PATH = "/resources/dist/.vite/manifest*.json";
  private static final String MANIFEST_KEY_PREFIX = "src/main/frontend/";
  private static final String SOURCE_PREFIX = ":frontend/";
  private static final String TARGET_DIR = "dist/";

  private final ResourcePatternResolver resourceLoader;
  private final ObjectMapper objectMapper;

  // ":frontend/file.ts" -> ("dist/file.a8b3.mjs", ["dist/assets/file.a8b3.css"])
  private final Supplier<Map<String, FrontendResource>> manifest = Suppliers.memoize(
      this::readManifestFiles);

  @Inject
  public FrontendResourceResolver(ResourcePatternResolver resourceLoader) {
    this.resourceLoader = resourceLoader;
    this.objectMapper = new ObjectMapper();
  }

  @PostConstruct
  public void init() {
    manifest.get();
  }

  public boolean isFrontendSource(String path) {
    return requireNonNullElse(path, "").trim().startsWith(SOURCE_PREFIX);
  }

  /**
   * Resolves a frontend source path to its emitted dist files.
   *
   * @param sourcePath
   *          e.g. ":frontend/file.ts"
   *
   * @return The resolved frontend resource with JS and CSS dist paths, e.g.
   *         "dist/file.a8b3.mjs" and ["dist/assets/file.a8b3.css"]
   */
  public Optional<FrontendResource> get(String sourcePath) {
    return Optional.ofNullable(manifest.get().get(sourcePath));
  }

  private Map<String, FrontendResource> readManifestFiles() {
    Resource[] resources;
    try {
      resources = resourceLoader.getResources(MANIFEST_PATH);
    } catch (IOException e) {
      throw new IllegalStateException("Failed loading frontend manifest files", e);
    }
    var map = StreamEx.of(resources)
        .filter(Resource::exists)
        .flatMap(this::readJson)
        .flatMap(rootNode -> StreamEx.of(rootNode.fields()))
        .mapToEntry(Entry::getKey, Entry::getValue)
        .flatMapKeys(this::prefixKey)
        .flatMapValues(this::extractResource)
        .toImmutableMap(); // ISE on duplicate keys, we expect unique source files
    LOGGER.info("readManifest - {}", map);
    return map;
  }

  private Stream<JsonNode> readJson(Resource resource) {
    try (InputStream is = resource.getInputStream()) {
      return Stream.ofNullable(objectMapper.readTree(is));
    } catch (IOException e) {
      LOGGER.error("Failed reading JSON from resource [{}]", resource.getFilename(), e);
      return Stream.empty();
    }
  }

  private Stream<String> prefixKey(String key) {
    return Stream.ofNullable(key)
        .filter(k -> k.startsWith(MANIFEST_KEY_PREFIX))
        .map(k -> k.replaceFirst(MANIFEST_KEY_PREFIX, SOURCE_PREFIX));
  }

  private Stream<FrontendResource> extractResource(JsonNode node) {
    return extractFilePath(node)
        .map(jsPath -> new FrontendResource(jsPath, extractCssPaths(node)))
        .stream();
  }

  private Optional<String> extractFilePath(JsonNode node) {
    return Optional.ofNullable(node)
        .map(n -> n.get("file"))
        .map(this::toTargetPath);
  }

  private List<String> extractCssPaths(JsonNode node) {
    return Optional.ofNullable(node)
        .map(n -> n.get("css"))
        .filter(JsonNode::isArray)
        .stream().flatMap(css -> StreamEx.of(css.elements()))
        .map(this::toTargetPath)
        .toList();
  }

  private String toTargetPath(JsonNode node) {
    return Optional.ofNullable(node)
        .map(f -> f.asText())
        .filter(f -> !f.isEmpty())
        .map(f -> TARGET_DIR + f)
        .orElse(null);
  }

  public record FrontendResource(String jsPath, List<String> cssPaths) {}
}
